Netwave ip camera password disclosure (#257)
* Netwave ip camera password disclosure

Netwave ip camera password disclosure exploit

* pep8

pep8

* PEP8 corrections

PEP8 corrections

* PEP8

PEP 8 corrections

* removed subproccess

replaced wget and grep with inter_content

* removed unused imports 

removed unused imports

* Implemented changes

changes implemented as suggested

* re-checked for weird character

re-checked for weird character

* corrected indent

IndentationError: expected an indented block

* deleted ^M

deleted ^M

* dos2unix for ^M deletion

dos2unix for ^M deletion

* deleted file

deleted file

* re-uploaded netwave_ipcamera.py

re-uploaded netwave_ipcamera.py

* Update netwave_IP_camera.py

* updated check method 

updated check method